In [1]:
import numpy as np

In [3]:
np.random.seed(0)
A = np.random.randint(0, 10, [5,5])
A

array([[5, 0, 3, 3, 7],
       [9, 3, 5, 2, 4],
       [7, 6, 8, 8, 1],
       [6, 7, 7, 8, 1],
       [5, 9, 8, 9, 4]])

# **Methode ndarray**

In [4]:
 A.sum(axis=1)

array([18, 23, 30, 29, 35])

In [5]:
A.cumsum()

array([  5,   5,   8,  11,  18,  27,  30,  35,  37,  41,  48,  54,  62,
        70,  71,  77,  84,  91,  99, 100, 105, 114, 122, 131, 135])

In [6]:
 A.min(axis=0)

array([5, 0, 3, 2, 1])

In [7]:
 A.argmin(axis=0)

array([0, 0, 0, 1, 2])

In [8]:
A.argsort()

array([[1, 2, 3, 0, 4],
       [3, 1, 4, 2, 0],
       [4, 1, 0, 2, 3],
       [4, 0, 1, 2, 3],
       [4, 0, 2, 1, 3]])

In [ ]:
np.exp(A)

array([[1.48413159e+02, 1.00000000e+00, 2.00855369e+01, 2.00855369e+01,
        1.09663316e+03],
       [8.10308393e+03, 2.00855369e+01, 1.48413159e+02, 7.38905610e+00,
        5.45981500e+01],
       [1.09663316e+03, 4.03428793e+02, 2.98095799e+03, 2.98095799e+03,
        2.71828183e+00],
       [4.03428793e+02, 1.09663316e+03, 1.09663316e+03, 2.98095799e+03,
        2.71828183e+00],
       [1.48413159e+02, 8.10308393e+03, 2.98095799e+03, 8.10308393e+03,
        5.45981500e+01]])

In [ ]:
np.log(A)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([[1.60943791,       -inf, 1.09861229, 1.09861229, 1.94591015],
       [2.19722458, 1.09861229, 1.60943791, 0.69314718, 1.38629436],
       [1.94591015, 1.79175947, 2.07944154, 2.07944154, 0.        ],
       [1.79175947, 1.94591015, 1.94591015, 2.07944154, 0.        ],
       [1.60943791, 2.19722458, 2.07944154, 2.19722458, 1.38629436]])

# **Statistique**

In [ ]:
A

array([[5, 0, 3, 3, 7],
       [9, 3, 5, 2, 4],
       [7, 6, 8, 8, 1],
       [6, 7, 7, 8, 1],
       [5, 9, 8, 9, 4]])

In [ ]:
A.mean()

5.4

In [ ]:
A.std()

2.6683328128252666

In [ ]:
A.var()

7.12

In [ ]:
np.corrcoef(A)

array([[ 1.        ,  0.39741307, -0.59190035, -0.77390599, -0.89934617],
       [ 0.39741307,  1.        ,  0.09521171, -0.11337365, -0.59181844],
       [-0.59190035,  0.09521171,  1.        ,  0.9579589 ,  0.6947088 ],
       [-0.77390599, -0.11337365,  0.9579589 ,  1.        ,  0.84515425],
       [-0.89934617, -0.59181844,  0.6947088 ,  0.84515425,  1.        ]])

In [ ]:
np.corrcoef(A)[0,1]

0.39741306906256163

In [ ]:
np.unique(A, return_counts=True)

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), array([1, 2, 1, 3, 2, 3, 2, 4, 4, 3]))

In [ ]:
values, counts = np.unique(A, return_counts=True)

In [ ]:
values

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
counts

array([1, 2, 1, 3, 2, 3, 2, 4, 4, 3])

In [ ]:
counts.argsort()

array([0, 2, 1, 4, 6, 3, 5, 9, 7, 8])

In [ ]:
values[counts.argsort()]

array([0, 2, 1, 4, 6, 3, 5, 9, 7, 8])

In [ ]:
for i, j in zip(values[counts.argsort()],counts[counts.argsort()]):
  print(f'valeur {i} apparait {j}')

valeur 0 apparait 1
valeur 2 apparait 1
valeur 1 apparait 2
valeur 4 apparait 2
valeur 6 apparait 2
valeur 3 apparait 3
valeur 5 apparait 3
valeur 9 apparait 3
valeur 7 apparait 4
valeur 8 apparait 4


In [ ]:
A = np.random.randn(5,5)
A[0, 2] = np.nan
A[4, 3] = np.nan
A

array([[ 0.44386323,  0.33367433,         nan, -0.20515826,  0.3130677 ],
       [-0.85409574, -2.55298982,  0.6536186 ,  0.8644362 , -0.74216502],
       [ 2.26975462, -1.45436567,  0.04575852, -0.18718385,  1.53277921],
       [ 1.46935877,  0.15494743,  0.37816252, -0.88778575, -1.98079647],
       [-0.34791215,  0.15634897,  1.23029068,         nan, -0.38732682]])

In [ ]:
np.nanmean(A)

0.010707879575141632

In [ ]:
np.nanvar(A)

1.213857100788078

In [ ]:
np.nanstd(A)

1.1017518326683546

In [ ]:
np.isnan(A)

array([[False, False,  True, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False,  True, False]])

In [ ]:
np.isnan(A).sum()

2

In [ ]:
np.isnan(A).sum()/A.size

0.08

In [ ]:
A[np.isnan(A)] = 0
A

array([[ 0.44386323,  0.33367433,  0.        , -0.20515826,  0.3130677 ],
       [-0.85409574, -2.55298982,  0.6536186 ,  0.8644362 , -0.74216502],
       [ 2.26975462, -1.45436567,  0.04575852, -0.18718385,  1.53277921],
       [ 1.46935877,  0.15494743,  0.37816252, -0.88778575, -1.98079647],
       [-0.34791215,  0.15634897,  1.23029068,  0.        , -0.38732682]])

# **Algebre Lineaire**

In [ ]:
A = np.ones((2, 3))
B = np.ones((3, 2))

In [ ]:
A

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
B

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [ ]:
A.T

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [ ]:
A.dot(B)

array([[3., 3.],
       [3., 3.]])

In [ ]:
B.dot(A)

array([[2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.]])

In [ ]:
A = np.random.randint(0, 10, [3, 3])
A

array([[3, 5, 9],
       [4, 4, 6],
       [4, 4, 3]])

In [ ]:
np.linalg.det(A)

23.999999999999993

In [ ]:
np.linalg.inv(A)

array([[-0.5       ,  0.875     , -0.25      ],
       [ 0.5       , -1.125     ,  0.75      ],
       [-0.        ,  0.33333333, -0.33333333]])

In [ ]:
np.linalg.pinv(A)

array([[-5.00000000e-01,  8.75000000e-01, -2.50000000e-01],
       [ 5.00000000e-01, -1.12500000e+00,  7.50000000e-01],
       [ 1.20555089e-17,  3.33333333e-01, -3.33333333e-01]])

In [ ]:
np.linalg.eig(A)

(array([13.58872344, -3.        , -0.58872344]),
 array([[-6.70561268e-01, -8.32050294e-01,  6.04408531e-01],
        [-5.73889829e-01,  2.12013389e-16, -7.73940635e-01],
        [-4.70104297e-01,  5.54700196e-01,  1.88960901e-01]]))

Exercice
Standardisez la matrice A sur chaque colonne:
(A-!A) / sig(A)
Resultat: chaque colonne doit avoir moyenne = 0 et ecart type = 1

In [ ]:
np.random.seed(0)
A = np.random.randint(0, 100, [10, 5])
A

array([[44, 47, 64, 67, 67],
       [ 9, 83, 21, 36, 87],
       [70, 88, 88, 12, 58],
       [65, 39, 87, 46, 88],
       [81, 37, 25, 77, 72],
       [ 9, 20, 80, 69, 79],
       [47, 64, 82, 99, 88],
       [49, 29, 19, 19, 14],
       [39, 32, 65,  9, 57],
       [32, 31, 74, 23, 35]])

# **Correction**

In [ ]:
D = (A - A.mean(axis=0)) / A.std(axis=0)

In [ ]:
D

array([[-0.02206157,  0.        ,  0.13173823,  0.72539252,  0.10755798],
       [-1.56637126,  1.61579632, -1.48676006, -0.33034307,  0.96802178],
       [ 1.12513992,  1.84021247,  1.03508612, -1.14768676, -0.27965074],
       [ 0.90452425, -0.35906585,  0.99744662,  0.0102168 ,  1.01104497],
       [ 1.6104944 , -0.44883231, -1.33620208,  1.0659524 ,  0.32267393],
       [-1.56637126, -1.21184724,  0.73397016,  0.7935045 ,  0.62383626],
       [ 0.11030784,  0.76301493,  0.80924915,  1.81518411,  1.01104497],
       [ 0.1985541 , -0.80789816, -1.56203905, -0.90929485, -2.17267111],
       [-0.24267724, -0.67324847,  0.16937773, -1.24985473, -0.32267393],
       [-0.55153918, -0.7181317 ,  0.50813319, -0.77307091, -1.26918412]])