1.   Contructeur: 
*   np.**array**
*   np.**zeros**
*   np.**random.randn**
*   ...
2.   shape, ndim, size
3.   dtype: **float16, float64**
4.   Manipulation:
     *   **concatenate, hstack, vstack**
     *   **reshape, squeeze**
     *   **ravel**
















In [1]:
import numpy as np

In [ ]:
A = np.array([1,2,3])
A.shape

(3,)

In [2]:
B = np.zeros((3,2))
type(B.shape)

tuple

In [3]:
C = np.ones((3,4))
C

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [4]:
D = np.full((2,3),9)
D

array([[9, 9, 9],
       [9, 9, 9]])

In [5]:
np.random.seed(2)
E = np.random.randn(3,4)
E

array([[-0.41675785, -0.05626683, -2.1361961 ,  1.64027081],
       [-1.79343559, -0.84174737,  0.50288142, -1.24528809],
       [-1.05795222, -0.90900761,  0.55145404,  2.29220801]])

In [6]:
np.full((3,4),5)

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [7]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [8]:
np.linspace(0, 10, 20, dtype=np.float16)

array([ 0.    ,  0.5264,  1.053 ,  1.579 ,  2.105 ,  2.63  ,  3.158 ,
        3.684 ,  4.21  ,  4.74  ,  5.26  ,  5.79  ,  6.316 ,  6.844 ,
        7.367 ,  7.895 ,  8.42  ,  8.945 ,  9.48  , 10.    ],
      dtype=float16)

In [9]:
np.arange(0,50,5)

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

# **Manipulation**

In [10]:
A1 = np.zeros((3,2))
B1 = np.ones((3,2))
B2 = np.full((3,2),5)

In [11]:
C1 = np.hstack((A1,B1))
C1.shape

(3, 4)

In [12]:
C2 = np.vstack((A1,B1))
C2.shape

(6, 2)

In [15]:
C3 = np.concatenate((A1,B1), axis=1)
C3

array([[0., 0., 1., 1.],
       [0., 0., 1., 1.],
       [0., 0., 1., 1.]])

In [16]:
C2 = C2.reshape((3,4))
C2

array([[0., 0., 0., 0.],
       [0., 0., 1., 1.],
       [1., 1., 1., 1.]])

In [19]:
AA = np.array([1,2,3])
AA = AA.reshape(AA.shape[0],1)
AA.shape

(3, 1)

In [20]:
AA.squeeze()

array([1, 2, 3])

In [ ]:
C2.ravel()

array([0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1.])

# **Exercice**

In [ ]:
#np.random.seed(0)
def initialisation(m,n):
  # m: nombre de lignes
  # n: nombre de colonnes
  # retourne une matrice aleatoire (m, n+1)
  # avec une colonne biais (remplie de "1") tout a droite

  MA1 = np.random.randn(m,n)

  MA2 = np.ones((m,1))

  MA = np.concatenate((MA1,MA2), axis=1)

  return MA

In [ ]:
m = int(input('Entrez la valeur de m \n'))
n = int(input('Entrez la valeur de n \n'))
#m = 5
#n = 4
initialisation(m,n)

Entrez la valeur de m 
5
Entrez la valeur de n 
4


array([[-0.67246045, -0.35955316, -0.81314628, -1.7262826 ,  1.        ],
       [ 0.17742614, -0.40178094, -1.63019835,  0.46278226,  1.        ],
       [-0.90729836,  0.0519454 ,  0.72909056,  0.12898291,  1.        ],
       [ 1.13940068, -1.23482582,  0.40234164, -0.68481009,  1.        ],
       [-0.87079715, -0.57884966, -0.31155253,  0.05616534,  1.        ]])

# **Correction**

In [ ]:
def initialisation1(m,n):
  # m: nombre de lignes
  # n: nombre de colonnes
  # retourne une matrice aleatoire (m, n+1)
  # avec une colonne biais (remplie de "1") tout a droite

  X = np.random.randn(m,n)
  X = np.concatenate((X, np.ones((X.shape[0],1))), axis=1)

  return X

In [ ]:
m = int(input('Entrez la valeur de m \n'))
n = int(input('Entrez la valeur de n \n'))
#m = 5
#n = 4
initialisation1(m,n)

Entrez la valeur de m 
5
Entrez la valeur de n 
4


array([[-1.04855297, -1.42001794, -1.70627019,  1.9507754 ,  1.        ],
       [-0.50965218, -0.4380743 , -1.25279536,  0.77749036,  1.        ],
       [-1.61389785, -0.21274028, -0.89546656,  0.3869025 ,  1.        ],
       [-0.51080514, -1.18063218, -0.02818223,  0.42833187,  1.        ],
       [ 0.06651722,  0.3024719 , -0.63432209, -0.36274117,  1.        ]])

# **YESSSSSSSSSSSSS**