In [1]:
x = -3
abs(x)

3

In [2]:
x1 = 5.123654
round(x1,3)

5.124

# **Conversion**

In [3]:
x2 = 10
type(x2)

int

In [4]:
x = str(x2)
x

'10'

In [5]:
type(x2)

int

In [6]:
y = '20'
y = int(y)
y

20

In [7]:
liste_1 = [0, 61, 63, 243]

In [8]:
tuple_1 = tuple(liste_1)
tuple_1

(0, 61, 63, 243)

# **Input**

In [9]:
x = int(input('Entrez un nombre'))
x + 10

Entrez un nombre2


12

# **Format()**

In [10]:
x3 = 25
ville = 'Paris'
message = "la temperature est de {} deg C a {}".format(x3, ville)
print(message)

la temperature est de 25 deg C a Paris


In [11]:
x3 = 25
ville = 'Paris'
message = f"la temperature est de {x} deg C a {ville}"
print(message)

la temperature est de 2 deg C a Paris


**avec FOR**

In [13]:
import numpy as np

In [14]:
parametres = {
    "W1": np.random.randn(2, 4),
    "B1": np.random.randn(2, 1),
    "W2": np.random.randn(2, 3),
    "B2": np.random.randn(2, 1)
}

In [15]:
for i in range(1,3):
  print("couche", i)
  print(parametres[f"W{i}"])

couche 1
[[ 0.17276272  1.3054605  -1.12946325  2.21543461]
 [-0.47419873 -0.03252369 -0.66229517  0.54425748]]
couche 2
[[-0.38711305  0.80051499  0.59045289]
 [-1.30611187  0.15355935 -1.15334965]]


# **Open**

In [16]:
f = open('fichier.txt', 'w')

In [17]:
f.write('Bonjour je m appelle Gibi')
f.close()

In [18]:
f = open('fichier.txt', 'r')
print(f.read())
f.close()

Bonjour je m appelle Gibi


In [19]:
with open('fichier.txt', 'r') as f:
  print(f.read())


Bonjour je m appelle Gibi


In [20]:
with open('fichier.txt', 'w') as f:
  for i in range(10):
    #f.write("{}^2 = {} \n".format(i, i**2))
    f.write(f"{i}^2 = {i**2} \n")

with open('fichier.txt', 'r') as f:
  print(f.read())


0^2 = 0 
1^2 = 1 
2^2 = 4 
3^2 = 9 
4^2 = 16 
5^2 = 25 
6^2 = 36 
7^2 = 49 
8^2 = 64 
9^2 = 81 



# **Exercise**
Utiliser la fonction "Open" pour lire ce "fichier.txt" et de retourner une liste
[0^2=0, 1^2=1, 2^2=4, ..., 9^2=81]

# **Reponse**

In [ ]:
with open('fichier1.txt', 'w') as f:
  for i in range(10):
    #f.write("{}^2 = {}".format(i, i**2))
    f.write(f"{i}^2 = {i**2}")

with open('fichier1.txt', 'r') as f:
  print(list(f.read()))


['0', '^', '2', ' ', '=', ' ', '0', '1', '^', '2', ' ', '=', ' ', '1', '2', '^', '2', ' ', '=', ' ', '4', '3', '^', '2', ' ', '=', ' ', '9', '4', '^', '2', ' ', '=', ' ', '1', '6', '5', '^', '2', ' ', '=', ' ', '2', '5', '6', '^', '2', ' ', '=', ' ', '3', '6', '7', '^', '2', ' ', '=', ' ', '4', '9', '8', '^', '2', ' ', '=', ' ', '6', '4', '9', '^', '2', ' ', '=', ' ', '8', '1']


# **Correction**

In [ ]:
with open('fichier2.txt', 'w') as f:
  for i in range(10):
    f.write(f"{i}^2 = {i**2} \n")

with open('fichier2.txt', 'r') as f:
  liste = f.readlines()
liste

['0^2 = 0 \n',
 '1^2 = 1 \n',
 '2^2 = 4 \n',
 '3^2 = 9 \n',
 '4^2 = 16 \n',
 '5^2 = 25 \n',
 '6^2 = 36 \n',
 '7^2 = 49 \n',
 '8^2 = 64 \n',
 '9^2 = 81 \n']

**Sans le "\n"**

In [ ]:
with open('fichier2.txt', 'r') as f:
  liste = f.read().splitlines()
liste

['0^2 = 0 ',
 '1^2 = 1 ',
 '2^2 = 4 ',
 '3^2 = 9 ',
 '4^2 = 16 ',
 '5^2 = 25 ',
 '6^2 = 36 ',
 '7^2 = 49 ',
 '8^2 = 64 ',
 '9^2 = 81 ']

**Avec les liste comprehension**

In [ ]:
liste = [line for line in open('fichier.txt', 'r')]
liste

['0^2 = 0 \n',
 '1^2 = 1 \n',
 '2^2 = 4 \n',
 '3^2 = 9 \n',
 '4^2 = 16 \n',
 '5^2 = 25 \n',
 '6^2 = 36 \n',
 '7^2 = 49 \n',
 '8^2 = 64 \n',
 '9^2 = 81 \n']

**Avec les liste comprehension et sans le "\n**

In [ ]:
liste = [line.strip() for line in open('fichier.txt', 'r')]
liste

['0^2 = 0',
 '1^2 = 1',
 '2^2 = 4',
 '3^2 = 9',
 '4^2 = 16',
 '5^2 = 25',
 '6^2 = 36',
 '7^2 = 49',
 '8^2 = 64',
 '9^2 = 81']