In [50]:
import numpy as np

# **BROADCASTING**

In [51]:
np.random.seed(0)
A = np.random.randint(0, 10, [2,3])
B = np.ones((2,3))

In [52]:
A

array([[5, 0, 3],
       [3, 7, 9]])

In [53]:
B

array([[1., 1., 1.],
       [1., 1., 1.]])

In [54]:
A + B

array([[ 6.,  1.,  4.],
       [ 4.,  8., 10.]])

In [55]:
np.random.seed(0)
A1 = np.random.randint(0, 10, [3,3])
B1 = np.ones((1,1))

In [56]:
A1

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2]])

In [57]:
B1

array([[1.]])

In [58]:
A1 + B1

array([[ 6.,  1.,  4.],
       [ 4.,  8., 10.],
       [ 4.,  6.,  3.]])

In [59]:
np.random.seed(0)
A2 = np.random.randint(0, 10, [4,1])
B2 = np.ones((1,3))

In [60]:
A2

array([[5],
       [0],
       [3],
       [3]])

In [61]:
B2

array([[1., 1., 1.]])

In [62]:
A2 + B2

array([[6., 6., 6.],
       [1., 1., 1.],
       [4., 4., 4.],
       [4., 4., 4.]])