In [25]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder

**LabelEncoder**

In [26]:
y = np.array(['chat', 'chien', 'chat', 'oiseau'])

In [27]:
encoder = LabelEncoder()
#encoder.fit(y)
encoder.fit_transform(y)


array([0, 1, 0, 2])

In [28]:
encoder.classes_

array(['chat', 'chien', 'oiseau'], dtype='<U6')

In [29]:
encoder.transform(y)

array([0, 1, 0, 2])

In [30]:
encoder.inverse_transform(np.array([0, 1, 0, 2]))

array(['chat', 'chien', 'chat', 'oiseau'], dtype='<U6')

**OrdinalEncoder**

In [31]:
from sklearn.preprocessing import OrdinalEncoder

In [32]:
X = np.array([['Chat', 'Poils'],
              ['Chien', 'Poils'],
              ['Chat', 'Poils'],
              ['Oiseau', 'Plumes']])

In [33]:
encoder = OrdinalEncoder()
encoder.fit_transform(X)

array([[0., 1.],
       [1., 1.],
       [0., 1.],
       [2., 0.]])

**LabelBinarizer**

In [34]:
from sklearn.preprocessing import LabelBinarizer

In [35]:
encoder = LabelBinarizer()
#encoder = LabelBinarizer(sparse_output=True)
encoder.fit_transform(y)

array([[1, 0, 0],
       [0, 1, 0],
       [1, 0, 0],
       [0, 0, 1]])

**One-Hot Encoder**

In [36]:
from sklearn.preprocessing import OneHotEncoder

In [37]:
encoder = OneHotEncoder()
encoder.fit_transform(X)

<4x5 sparse matrix of type '<class 'numpy.float64'>'
	with 8 stored elements in Compressed Sparse Row format>

**Normalisation MinMax**

In [38]:
from sklearn.preprocessing import MinMaxScaler

In [39]:
X = np.array([[70],
             [80],
             [120]])

In [40]:
encoder = MinMaxScaler()
encoder.fit_transform(X)

array([[0. ],
       [0.2],
       [1. ]])

In [41]:
from sklearn.datasets import load_iris

In [42]:
iris = load_iris()
X = iris.data

X_minmax = MinMaxScaler().fit_transform(X)

plt.scatter(X[:,2], X[:,3], alpha=0.5, label='original')
plt.scatter(X_minmax[:,2], X_minmax[:,3], alpha=0.5, label='minmax')
plt.legend()
plt.show()

**Standardisation**

In [ ]:
from sklearn.preprocessing import StandardScaler, RobustScaler

In [ ]:
X = np.array([[70],
             [80],
             [120]])

In [ ]:
encoder = StandardScaler()
encoder.fit_transform(X)

array([[-0.9258201 ],
       [-0.46291005],
       [ 1.38873015]])

In [ ]:
%matplotlib
iris = load_iris()
X = iris.data

outliers = np.full((10, 4), 100) + np.random.randn(10, 4)
X = np.vstack((X, outliers))

X_minmax = MinMaxScaler().fit_transform(X)
X_stdscl = StandardScaler().fit_transform(X)
X_robust = RobustScaler().fit_transform(X)

plt.scatter(X[:,2], X[:,3], alpha=0.5, label='original')
plt.scatter(X_minmax[:,2], X_minmax[:,3], alpha=0.5, label='MinMaxScaler')
plt.scatter(X_stdscl[:,2], X_stdscl[:,3], alpha=0.5, label='StandardScaler')
plt.scatter(X_robust[:,2], X_robust[:,3], alpha=0.5, label='RobustScaler')
plt.legend()
#plt.show()

Using matplotlib backend: agg
